# Generated by Django 5.0.1 on 2024-02-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=45)),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_quantity_received', models.IntegerField(default=0)),
                ('item_type_id', models.IntegerField(null=True)),
                ('requests_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_type',
            fields=[
                ('item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=45)),
                ('request_type', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='request_status',
            fields=[
                ('request_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_status_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='request_type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('requests_id', models.AutoField(primary_key=True, serialize=False)),
                ('requests_status_id', models.IntegerField()),
                ('donate_user_id', models.IntegerField(default=0, null=True)),
                ('receive_user_id', models.IntegerField()),
                ('location_lat', models.FloatField(null=True)),
                ('location_long', models.FloatField(null=True)),
                ('area', models.CharField(max_length=45, null=True)),
                ('info', models.CharField(max_length=45, null=True)),
                ('type_id', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=45, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('schedule_date', models.DateField(null=True)),
                ('schedule_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='unit_img',
            fields=[
                ('u_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(default='default.png', max_length=45)),
                ('unit_name', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
