# Generated by Django 5.0.1 on 2024-02-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_donation_items_item_type_request_status_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='area',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='requests',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='donate_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requests',
            name='info',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='requests',
            name='location_lat',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='requests',
            name='location_long',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='requests',
            name='schedule_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='requests',
            name='schedule_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='requests',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='type_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='requests',
            name='unit',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
