# Generated by Django 5.0.1 on 2024-02-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_requests_requests_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='item_type_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
