# Generated by Django 5.0.1 on 2024-02-28 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_donation_items_item_type_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='receive_user_id',
        ),
        migrations.AddField(
            model_name='requests',
            name='requestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
