# Generated by Django 5.0.1 on 2024-02-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_requests_receive_user_id_requests_requestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='item_name',
            field=models.CharField(default='not yet defined', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='donation_items',
        ),
    ]
