# Generated by Django 5.0.1 on 2024-03-03 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_requests_item_name_requests_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='requests_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.request_status'),
        ),
    ]
